### ISSUE TITLE
Indicate how far along a user is in the convo to reduce survey fatigue

### ISSUE THREAD

**Issue by BrandonAnderson** [Raheem-ai/raheem-bot#11]
Users should know about how far along they are in the conversation. Maybe a progress bar?

**Comment by Jlawlzz** [comment]
We can't show a literal progress bar (facebook doesn't support that type of thing) but we could fake a progress bar via picture. otherwise we can just do this verbally.

**Comment by BrandonAnderson** [comment]
How would the image of a progress bar work without it being clunky? I like the idea, but wanna make sure it's seamless.

**Comment by BrandonAnderson** [comment]
Placed copy up front that states: "This will take about five minutes."
