### ISSUE TITLE
Starting new communication with bot after timeout results in lost data

### ISSUE THREAD

**Issue by jhankin** [Raheem-ai/raheem-bot#2]
Repro steps:

1.) Start a report but don't finish it.  In my case, I left off at the attachments phase.
2.) Wait for a while, such that the session with the bot times out.  In my case, this was six days.
3.) Start a new report.  In my case, I just said "I had an incident" and the bot responded with the initial "Hi, I'm Raheem" script.
4.) No `POST /incident` or subsequent `PATCH /incident/#id` calls will be made and thus no `incident` record will be created on the backend.  All data will be dropped on the floor.

**Comment by Jlawlzz** [comment]
@jhankin this is due to redis store being disabled.  Will re-initialize today, stay tuned.

**Comment by jhankin** [comment]
@Jlawlzz just confirmed this is still happening.  We have to make sure if someone leaves off in the middle of a convo, that their next convo isn't lost.

**Comment by jhankin** [comment]
Saw this again after about a 5-hour timeout.
