### ISSUE TITLE
incident_type_name should be populated from INITIAL_CONTACT field

### ISSUE THREAD

**Issue by jhankin** [Raheem-ai/raheem-bot#3]
Currently, the bot is sending the param `incident_type_name` with the contents of `CONTACT_OUTCOME`.  That field should be populated with the contents of `INITIAL_CONTACT` instead.

**Comment by Jlawlzz** [comment]
@jhankin Updated and working: 

{
  "data": {
    "id": 817,
    "slug": "oD98DYVz",
    "user_id": 21,
    **"incident_type_id": 3,**
    "description": null,
    "start_time": "2017-03-27T00:00:00Z",
    "location": null,
    "reactions_list": "",
    "tags_list": "",
    "latitude": 37.450696292476,
    "longitude": -122.18158373915,
    "address": "715 Live Oak Ave, Menlo Park, CA 94025, USA",
    "rating": null,
    "completed": false,
    "metadata": "{\"DATE_OF_INCIDENT\":1490572800,\"TIME_OF_INCIDENT\":\"12:34pm\",\"ENCOUNTER_LOCATION\":\"{\\\"lat\\\":37.450696292476,\\\"long\\\":-122.18158373915}\",\"CONTACT_OUTCOME\":\"conversation\",\"CASE_NUMBER\":\"didn't get one\",\"INITIAL_CONTACT\":\"called the police\",\"POLICE_ACTION\":\"helped you\",\"POLICE_SEARCH?\":\"yes\",\"PERMISSION_TO_SEARCH?\":\"yes\"}",
    "created_at": "2017-03-27T16:54:03Z",
    "updated_at": "2017-03-27T16:55:01Z",
    "user": {
      "id": 21,
      "uid": "3e80f71d",
      "facebook_id": "1147770265316468",
      "created_at": "2016-10-07T17:42:31Z",
      "updated_at": "2017-03-21T06:04:58Z",
      "race_id": 3,
      "gender_id": 36,
      "religion_id": null,
      "birthday": "1970-01-01"
    },
    "attachments": [],
    "officers": []
  },
  "meta": {
    "status": 200
  }
}
