### ISSUE TITLE
Pre-populate quick replies to include the ranges for number of officers included in an incident.

### ISSUE THREAD

**Issue by BrandonAnderson** [Raheem-ai/raheem-bot#8]
> "About how many officers were at the scene?"

Pre-populate quick replies to include the number of officers instead of asking user to type. I suggest using a range (e.g. "1, 2-4, 5-7, 8-10, more than 10").

- If user selects "1" then bot goes straight to officer questions. 
- If user selects anything else, bot asks "did you talk to an officer in particular".

![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/12467495/24728063/423e010a-1a0d-11e7-966b-d6b9635791bd.jpg)

**Comment by Jlawlzz** [comment]
Good idea
